---
  - hosts: localhost
    connection: local
    vars:
      default_profil: "dev"

    tasks:
      - name: Read a json file
        set_fact:
          rabbitmq_conf:  "{{ lookup('file', './json/{{ default_profil }}/rabbitmq-conf.json') }}"
          exchanges_list:  "{{ lookup('file', './json/{{ default_profil }}/exchanges.json') }}"
          vhosts_list: "{{ lookup('file', './json/{{ default_profil }}/vhosts.json') }}"
          users_list: "{{ lookup('file', './json/{{ default_profil }}/users.json') }}"
          users_perms_list: "{{ lookup('file', './json/{{ default_profil }}/users-perms.json') }}"

      - name: What did we read?
        debug:
          var: vhosts_list

      - name: Affichage
        command: "echo {{ item.username }} ==> {{ item.password }}"
        with_items: "{{ users_list }}"

      - name: Create vhosts
        uri:
          url: "{{ rabbitmq_conf.rabbitmq_api_uri }}/vhosts/{{ item }}"
          user: "{{ rabbitmq_conf.rabbitmq_login }}"
          password: "{{ rabbitmq_conf.rabbitmq_password }}"
          method: PUT
          force_basic_auth: yes
          status_code: 
            - 204
            - 201
        with_items: "{{ vhosts_list }}"

      - name: Create exchanges
        uri:
          url: "{{ rabbitmq_conf.rabbitmq_api_uri }}/exchanges/{{ item.vhost }}/{{ item.exchange }}"
          user: "{{ rabbitmq_conf.rabbitmq_login }}"
          password: "{{ rabbitmq_conf.rabbitmq_password }}"
          method: PUT
          force_basic_auth: yes
          body_format: json
          body: 
            type: "topic"
            durable: true
          status_code: 
            - 204
            - 201
        with_items: "{{ exchanges_list }}"        

      - name: Create users
        uri:
          url: "{{ rabbitmq_conf.rabbitmq_api_uri }}/users/{{ item.username }}"
          user: "{{ rabbitmq_conf.rabbitmq_login }}"
          password: "{{ rabbitmq_conf.rabbitmq_password }}"
          method: PUT
          force_basic_auth: yes
          body_format: json
          body: 
            password: "{{ item.password }}"
            tags: "{{ item.tags }}"
          status_code: 
            - 204
            - 201
        with_items: "{{ users_list }}"       

      - name: Create users perms
        uri:
          url: "{{ rabbitmq_conf.rabbitmq_api_uri }}/permissions/{{ item.vhost }}/{{ item.username }}"
          user: "{{ rabbitmq_conf.rabbitmq_login }}"
          password: "{{ rabbitmq_conf.rabbitmq_password }}"
          method: PUT
          force_basic_auth: yes
          body_format: json
          body: 
            configure: "{{ item.configure }}"
            write: "{{ item.write }}"
            read: "{{ item.read }}"       
          status_code: 
            - 204
            - 201
        with_items: "{{ users_perms_list }}"            
